version: "3.9"

services:
  mongodb:
    restart: always
    image: mongo:4.4
    container_name: 'mongodb'
    environment:
        MONGO_INITDB_ROOT_USERNAME: 'admin'
        MONGO_INITDB_ROOT_PASSWORD: 'admin'
        MONGO_INITDB_DATABASE: 'snippets_db'
    ports:
        - 27017:27017
    volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        - ~/mongodb/data:/data/db
    networks: 
      - snippets-net

  backend:
    restart: always
    container_name: backend
    command: bash -c "python check_db.py --service-name mongodb --ip mongodb --port 27017 &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on: 
      - mongodb
    networks: 
      - snippets-net

  frontend:
    restart: always
    command: yarn start
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on: 
      - backend
    networks: 
      - snippets-net

networks:
  snippets-net:
    driver: bridge
